### ISSUE TITLE
Twitter::format ignored in Twitter::getSearchTweets

### ISSUE THREAD

**Issue by KIVagant** [pingpong-labs/twitter#18]
Request:
```
Twitter::format('JSON');
$params = ['q' => 'something', 'result_type' => 'recent'];
$result = Twitter::getSearchTweets($params, false, false);
var_dump($result);
```

Result:
```
object(stdClass)[235]
  public 'statuses' => 
    array (size=15)
      0 => 
        object(stdClass)[236]
...
```

Questions:
1. Why stdClass is returned?
2. Is Twitter::getSearchTweets has a pagination helpers support? Or I need always use twitter API params for this?

**Comment by gravitano** [comment]
Hi @KIVagant,

1. stdClass is the default result from third-party package that used by this package.
2. Try via twitter API params.

**Comment by KIVagant** [comment]
@gravitano , what is Twitter::format('JSON') doing?

**Comment by gravitano** [comment]
Hmm, let me fix this issue.

**Comment by gravitano** [comment]
I've been fixed this issue and this package also just tagged to new version `2.0.3`. Update your package and let me know if you still get this error. Thanks!

**Comment by KIVagant** [comment]
It seems to be working. Thank you!
