### ISSUE TITLE
Support of Laravel 5.1

### ISSUE THREAD

**Issue by hemulya** [pingpong-labs/twitter#19]
Hi @pingpong-labs

Can you please add support of laravel 5.1

Thanks.

**Comment by gravitano** [comment]
Hi @yariks, I would add support for Laravel 5.1 in next release of this package. Thanks!

**Comment by nicklee1990** [comment]
any word on when this is coming?

**Comment by wutmikee** [comment]
Any update on Laravel 5.1 release?

**Comment by gravitano** [comment]
Hey all, for Laravel 5.1 use pingpong/twitter version 2.1.*. Thanks!
